### ISSUE TITLE
rake aborted!

### ISSUE THREAD

**Issue by claudiocolaluce** [Smile-SA/redmine_smile_project_enumerations_custom_field_format#12] opened 2020-05-11 10:04 UTC
Environment:
Redmine version 4.0.1.devel
ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-linux]
Rails version 5.2.2

Other plugins installed are (gives the same error even without any plugin installed):
Agile redmine
Redmine checklists
<pre>
rake aborted!
ProjectsHelper MISS   instance_methods  project_settings_tabs_with_project_enumerations  < (SM::HO::ProjectsOverride::ProjectEnumerations)
/opt/redmine/redmine-4.0.1/plugins/redmine_smile_project_enumerations_custom_field_format-master/lib/helpers/smile_helpers_projects.rb:144:in `prepended'
/opt/redmine/redmine-4.0.1/plugins/redmine_smile_project_enumerations_custom_field_format-master/init.rb:74:in `prepend'
/opt/redmine/redmine-4.0.1/plugins/redmine_smile_project_enumerations_custom_field_format-master/init.rb:74:in `prepend_in'
/opt/redmine/redmine-4.0.1/plugins/redmine_smile_project_enumerations_custom_field_format-master/init.rb:164:in `block in <top (required)>'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:426:in `instance_exec'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `catch'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:199:in `block in halting'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `each'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `invoke_before'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:131:in `run_callbacks'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.2/lib/active_support/reloader.rb:89:in `prepare!'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/railties-5.2.2/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
/opt/redmine/redmine-4.0.1/config/environment.rb:14:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/railties-5.2.2/lib/rails/application.rb:337:in `require_environment!'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/railties-5.2.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/opt/redmine/redmine-4.0.1/lib/tasks/redmine.rake:57:in `block (2 levels) in <top (required)>'
/opt/redmine/.rvm/gems/ruby-2.5.7/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-2.5.7/bin/ruby_executable_hooks:24:in `eval'
/opt/redmine/.rvm/gems/ruby-2.5.7/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
</pre>

**Comment by claudiocolaluce** [comment] 2020-05-21 07:27
Hi Guys, I was hoping that some of you could help me! Thanks for what you do!

**Comment by claudiocolaluce** [comment] 2020-05-22 14:48
@Utopism

**Comment by Utopism** [comment] 2021-03-24 22:53
Hi, probably a compatibility issue with one of the two other plugins that you have.

**Comment by Utopism** [comment] 2021-03-24 23:09
* Redmine checklist seems not to be the cause even if this plugin is making unclean overrides.

**Comment by Utopism** [comment] 2021-03-24 23:19
Can you retry with the last plugin version (V1.3.15) ?

**Comment by Utopism** [comment] 2021-04-09 21:06
I am closing this issue because I have no reply from @claudiocolaluce, I will re-open it if I get news from him.

**Closed as completed by Utopism** 2021-04-09 21:06 UTC
