### ISSUE TITLE
Mobile App problem

### ISSUE THREAD

**Issue by HemishT** [Smile-SA/redmine_smile_project_enumerations_custom_field_format#1] opened 2019-10-11 21:45 UTC
In mobile applications  the values of custom field not show.

**Comment by Utopism** [comment] 2019-10-14 18:02
Hi, project enumerations are custom field values like List type custom field, so there is no specific behaviour for Mobile apps. Can you give us screen captures ?

**Comment by HemishT** [comment] 2019-10-15 21:00
Hi, custom field not show value, only id of value. See atached image.
![Screenshot_20191015-225219_RedminePM](https://user-images.githubusercontent.com/56456746/66869234-36382b00-ef9f-11e9-912e-da144d6d3d63.jpg)
![Screenshot_20191015-225345_Chrome](https://user-images.githubusercontent.com/56456746/66869235-36d0c180-ef9f-11e9-9c65-bff2a86f70e5.jpg)

**Comment by Utopism** [comment] 2019-10-15 21:47
Hi,
I think the mobile app uses the json api to display the issue, and the json view returns the id and not the value.
I checked and this is the same for a Custom Field of type **Version** or for a Custom Field of type **Key / Value**.
So it's not an issue in this plugin.
I don't think it is a native Redmine issue. I think it's more an issue in the mobile app that does not translate the id to a value in it's view layer.

Can you check if this is the same with a Custom Field of type Key / Value for example ?
It the value is displayed, you'll have to wait that this plugin is integrated in Redmine core (if it will be).
If not, you can fill a bug report to the Native app.

**Comment by Utopism** [comment] 2019-11-29 23:14
Hi @HemishT any further informations ?
I am going to close this issue as it not an issue of this plugin.

**Comment by HemishT** [comment] 2019-11-30 09:48
Hi,
I tried more apps and all have same issue, standart custom field is working without issue.

**Comment by Utopism** [comment] 2019-12-02 21:25
Hi,
What do you mean by Standard Custom Field ? Do you have found an App that displays the Value for a Key/Value type Custom Field, for example ?

**Comment by Utopism** [comment] 2020-04-19 00:57
Hi, I close this issue since it's not this plugin that is the cause of it.

**Closed as completed** 2020-04-19 00:57 UTC
